### ISSUE TITLE
Expected umbrella, header, submodule, or module export, could not build module

### ISSUE THREAD

**Issue by TopBananaHub** [chrisballinger/ProxyKit#13]
I have two errors during building: 
1)
CocoaLumberjack.framework/Modules/module.modulemap:7:2: error: expected umbrella, header, submodule, or module export
        textual header "DDLogMacros.h"
        ^

2)
Pods/ProxyKit/ProxyKit/Client/GCDAsyncProxySocket.m:11:9: fatal error: could not build module 'CocoaLumberjack'
@import CocoaLumberjack;

XCode 6.2
Build-target: os x 10.9

Tell me please, what's wrong.

**Comment by chrisballinger** [comment]
Upgrade to Xcode 7.3
