### ISSUE TITLE
Update dependency version of GCDAsyncSocket pod

### ISSUE THREAD

**Issue by raxcat** [chrisballinger/ProxyKit#15]
https://github.com/robbiehanson/CocoaAsyncSocket/blob/7.5.0/Source/GCD/GCDAsyncSocket.h#L1048 
CococAsyncSocket v7.5.0 still use the following declaration. 
`@protocol GCDAsyncSocketDelegate`

But in the the un-released version v7.5.1 the statement has been correctly.
`@protocol GCDAsyncSocketDelegate<Object>`

podspec:  dependency of  CocoaAsyncSocket should be updated after/if CocoaAsyncSocket is released

**Comment by chrisballinger** [comment]
I really should get around to that

**Comment by raxcat** [comment]
Thank you :)

**Comment by chrisballinger** [comment]
Done
