### ISSUE TITLE
Wrong replies

### ISSUE THREAD

**Issue by whisper-bye** [chrisballinger/ProxyKit#17]
@chrisballinger 
https://github.com/chrisballinger/ProxyKit/blob/master/ProxyKit/Server/SOCKSProxySocket.m#L269

The handshake's reply is wrong, responseBytes[3] = 3; only suitable for DOMAINNAME type,
In some strict uses will be an error, Tcp connection is canceled.

**Comment by chrisballinger** [comment]
Pull requests are welcome
